output: library.tsv.gz
filter:
  mode: FALSE
  level: kingdom # domain, phylum, class, order, family, tribe, genus, species, varietas
  value: Streptophyta # OR can be used as "|" example: Simaroubaceae|Gentianaceae