name: "Tag latest release of action tagger :zap:"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tag-latest:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - uses: ./
        with:
          publish_latest_tag: true
          prefer_branch_releases: false
